<?php
require_once File::build_path(array("model", 'Model.php'));

class ModelUniteDEnseignement extends Model
{

    protected static $primary = 'nUe';
    protected static $object = 'UniteDEnseignement';

    private $nUE;
    private $codeDiplome;
    private $idUE;
    private $semestre;
    private $heuresTP;
    private $heuresTD;
    private $heuresCM;

    /**
     * @return mixed
     */
    public function getIdUE()
    {
        return $this->idUE;
    }

    /**
     * @return mixed
     */
    public function getSemestre()
    {
        return (int)$this->semestre;
    }

    /**
     * @return mixed
     */
    public function getHeuresTP()
    {
        return (int)$this->heuresTP;
    }

    /**
     * @return mixed
     */
    public function getHeuresTD()
    {
        return (int)$this->heuresTD;
    }

    /**
     * @return mixed
     */
    public function getHeuresCM()
    {
        return (int)$this->heuresCM;
    }

    /**
     * @return mixed
     */
    public function getNUE()
    {
        return $this->nUE;
    }

    /**
     * @return mixed
     */
    public function getCodeDiplome()
    {
        return $this->codeDiplome;
    }

    /**
     * @param mixed $codeDiplome
     */
    public function setCodeDiplome($codeDiplome)
    {
        $this->codeDiplome = $codeDiplome;
    }

    public static function selectAll()
    {
        $retourne = parent::selectAll(); // TODO: Change the autogenerated stub
        foreach ($retourne as $cle => $item) {
            $retourne[$cle]->setCodeDiplome(ModelDiplome::select($item->getCodeDiplome()));
        }
    }

    public static function select($primary_value)
    {
        $retourne = parent::select($primary_value); // TODO: Change the autogenerated stub
        if (!$retourne) return false;
        $retourne->setCodeDiplome(ModelDiplome::select($retourne->getCodeDiplome()));
        return $retourne;
    }

    public static function selectAllByDiplome($codeDiplome)
    {
        try {
            $sql = 'SELECT * FROM ' . self::$object . ' WHERE codeDiplome=:codeDiplome';
            $rep = Model::$pdo->prepare($sql);
            $values = array('codeDiplome' => $codeDiplome);
            $rep->execute($values);
            $rep->setFetchMode(PDO::FETCH_CLASS, 'ModelUniteDEnseignement');
            $retourne = $rep->fetchAll();
            foreach ($retourne as $cle => $item) {
                $retourne[$cle]->setCodeDiplome(ModelDiplome::select($item->getCodeDiplome()));
            }
            return $retourne;
        } catch (Exception $e) {
            return false;
        }
    }

    public static function selectBy($codeDiplome, $semestre, $idUE)
    {
        try {
            $sql = 'SELECT * FROM ' . self::$object . ' WHERE codeDiplome=:codeDiplome AND semestre=:semestre AND idUE=:idUE';
            $rep = Model::$pdo->prepare($sql);
            $values = array(
                'codeDiplome' => $codeDiplome,
                'semestre' => $semestre,
                'idUE' => $idUE);
            $rep->execute($values);
            $rep->setFetchMode(PDO::FETCH_CLASS, 'ModelUniteDEnseignement');
            $retourne = $rep->fetchAll();
            if(empty($retourne)) return false;
            $retourne[0]->setCodeDiplome(ModelDiplome::select($retourne[0]->getCodeDiplome()));
            return $retourne[0];
        } catch (Exception $e) {
            return false;
        }
    }

    public function getVolumeHoraire()
    {
        return $this->getHeuresCM() + $this->getHeuresTD() + $this->getHeuresTP();
    }

    public function nommer()
    {
        return $this->getSemestre().$this->getIdUE();
    }


}